language: ruby
services:
- mongodb
rvm:
- '2.2'
sudo: false
before_install:
- npm install -g gulp bower
- npm prune
- bower prune
install:
- bundle install -j4 --path vendor/bundle
- npm install
before_script:
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rake spec
- gulp test
cache:
  directories:
  - vendor/bundle
env:
  global:
  - DISPLAY=":99.0"
deploy:
  provider: heroku
  api_key:
    secure: Flto68FNq2vnx9gqUqxYkO2gnVaVddBrITewWCzjau1aYzTRzw7Tt/JYtBXkAvhDVaIl9ot6Gd+Y6Vtlv9ws4GVipiOZWh1qHngOVNP5fo7hbxCelzzhQgyd4/x08gpY4855BeuoFBwGbjGhqq4J2MmCkf1PaGJ6ud5QGsNhJHo=
  app:
    production: cfhack
    development: cfhack-test

