language: ruby

services:
  - mongodb

rvm:
  - "2.2"

sudo: false

before_install:
  - npm install -g gulp bower
  - npm prune
  - bower prune

install:
  - bundle install -j4 --path vendor/bundle
  - npm install

script:
  - bundle exec rake spec
  - gulp test

cache:
  directories:
    - vendor/bundle

